import { useState } from "react";
import { motion } from "framer-motion";
import { Clapperboard, Play, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

interface FlagshipPromoProps {
  onLaunchPromo: () => void;
}

export function FlagshipPromo({ onLaunchPromo }: FlagshipPromoProps) {
  const [quickPrompt, setQuickPrompt] = useState("");

  return (
    <motion.section
      initial={{ opacity: 0, y: 30 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, margin: "-50px" }}
      transition={{ duration: 0.6 }}
      className="max-w-7xl mx-auto px-4 sm:px-6"
    >
      <div className="relative rounded-2xl overflow-hidden border border-border/30 bg-card/40 backdrop-blur-xl">
        {/* Animated grid bg */}
        <div className="absolute inset-0 opacity-[0.03]" style={{
          backgroundImage: "linear-gradient(hsl(var(--primary) / 0.3) 1px, transparent 1px), linear-gradient(90deg, hsl(var(--primary) / 0.3) 1px, transparent 1px)",
          backgroundSize: "40px 40px",
        }} />

        <div className="relative z-10 grid lg:grid-cols-2 gap-8 p-8 lg:p-12">
          {/* Left */}
          <div className="space-y-5">
            <div className="flex items-center gap-2">
              <div className="h-8 w-8 rounded-lg bg-primary/10 flex items-center justify-center">
                <Clapperboard className="h-4 w-4 text-primary" />
              </div>
              <span className="text-xs font-semibold text-primary uppercase tracking-wider">Flagship Tool</span>
            </div>

            <h2 className="text-2xl sm:text-3xl font-bold text-foreground tracking-tight">
              Short-Form Promo Generator
            </h2>
            <p className="text-sm text-muted-foreground leading-relaxed max-w-md">
              Turn any product into a scroll-stopping promo in seconds. Script, storyboard, and frame visuals — all generated by AI.
            </p>

            <div className="flex gap-2">
              <Input
                value={quickPrompt}
                onChange={(e) => setQuickPrompt(e.target.value)}
                placeholder="Describe what you want to create…"
                className="flex-1 bg-background/50 border-border/50"
              />
              <Button onClick={onLaunchPromo} className="btn-premium rounded-xl gap-2 px-5 shrink-0">
                <Sparkles className="h-4 w-4" /> Generate
              </Button>
            </div>
          </div>

          {/* Right — Preview mock */}
          <div className="flex items-center justify-center">
            <div className="relative w-[200px] h-[360px] rounded-2xl border border-border/30 bg-gradient-to-b from-card to-background overflow-hidden flex flex-col items-center justify-center gap-3">
              {/* Glowing border */}
              <div className="absolute inset-0 rounded-2xl ring-1 ring-inset ring-primary/10" />
              <Play className="h-12 w-12 text-primary/30" />
              <span className="text-[10px] text-muted-foreground">Preview</span>
              {/* Bottom glow */}
              <div className="absolute bottom-0 left-0 right-0 h-24 bg-gradient-to-t from-primary/5 to-transparent" />
            </div>
          </div>
        </div>
      </div>
    </motion.section>
  );
}
